#!/bin/bash

# Description
# Print some usefull information about your system.

# global variables
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')
greentext="\033[32m"
bold="\033[1m"
normal="\033[0m"
logdate=$(date +"%Y%m%d")
logfile="$logdate"_report.log

echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
printf "\n"
printf "System type: \t%s\n" $MACHTYPE
printf "Bash version: \t%s\n" $BASH_VERSION
printf "Free Space: \t%s\n" $freespace
printf "Files in dir: \t%s\n" $(ls | wc -l)
printf "Generate on: \t%s\n" $(date +%m/%d/%y) # US date fromat
printf "\n"
echo -e $greentext"A summary of this info has been saved to $logfile"$normal

cat <<- EOF > $logfile
	This report was automatically generated by my Bash script.
	It contains a brief summary of some system information.
EOF

printf "SYS: \t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile